In [2]:
import random

# random float in [0,1)
a = random.random()
print(a)

# random float in range [a,b]
a = random.uniform(1,10)
print(a)

# random integer in range [a,b]. b is included
a = random.randint(1,10)
print(a)

# random integer in range [a,b). b is excluded
a = random.randrange(1,10)
print(a)

# random float from a normal distribution with mu and sigma
a = random.normalvariate(0, 1)
print(a)

# choose a random element from a sequence
a = random.choice(list("ABCDEFGHI"))
print(a)

# choose k unique random elements from a sequence
a = random.sample(list("ABCDEFGHI"), 3)
print(a)

# choose k elements with replacement, and return k sized list
a = random.choices(list("ABCDEFGHI"),k=3)
print(a)

# shuffle list in place
a = list("ABCDEFGHI")
random.shuffle(a)
print(a)

0.8736063322291163
4.145114620868867
4
2
-0.4708309330944774
B
['D', 'C', 'H']
['A', 'A', 'F']
['E', 'H', 'B', 'A', 'G', 'D', 'I', 'F', 'C']


In [5]:
#The seed() method is used to initialize the random number generator. 
#reprodce same data
#The random number generator needs a number to start with (a seed value), to be able to generate a random number. 
#By default the random number generator uses the current system time.

print(random.random())
print(random.uniform(1,10))
print(random.choice(list("ABCDEFGHI")))
random.seed(1)
print(random.random())
print(random.uniform(1,10))
print(random.choice(list("ABCDEFGHI")))
random.seed(1)
print(random.random())
print(random.uniform(1,10))
print(random.choice(list("ABCDEFGHI")))

random.seed(2)
print(random.random())
print(random.uniform(1,10))
print(random.choice(list("ABCDEFGHI")))
random.seed(2)
print(random.random())
print(random.uniform(1,10))
print(random.choice(list("ABCDEFGHI")))

0.2550690257394217
5.458915783827469
H
0.13436424411240122
8.626903632435095
B
0.13436424411240122
8.626903632435095
B
0.9560342718892494
9.530447383534144
A
0.9560342718892494
9.530447383534144
A


In [9]:
#sectrets 
#The secrets module is used for generating cryptographically strong random numbers suitable for managing data 
#such as passwords, account authentication, security tokens, and related secrets.

import secrets
# random integer in range [0, n).
a = secrets.randbelow(10)
print(a)

# return an integer with k random bits. 5 bits mean 5 diff random bin values
a = secrets.randbits(5)
print(a)

# choose a random element from a sequence
a = secrets.choice(list("ABCDEFGHI"))
print(a)

9
3
F


In [16]:
#Create random numbers for nd arrays. 
#The NumPy pseudorandom number generator is different from the Python standard library 
#pseudorandom number generator.
#Importantly, seeding the Python pseudorandom number generator does not impact 
#the NumPy pseudorandom number generator. It must be seeded and used separately.


import numpy as np

np.random.seed(1)
# rand(d0,d1,…,dn)
# generate nd array with random floats, arrays has size (d0,d1,…,dn)
print(np.random.rand(3))
# reset the seed
np.random.seed(1)
print(np.random.rand(3))

# generate nd array with random integers in range [a,b) with size n
values = np.random.randint(0, 10, (5,3))
print(values)

# generate nd array with Gaussian values, array has size (d0,d1,…,dn)
# values from standard normal distribution with mean 0.0 and standard deviation 1.0
values = np.random.randn(5)
print(values)

# randomly shuffle a nd array.
# only shuffles the array along the first axis of a multi-dimensional array
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
np.random.shuffle(arr)
print(arr)


[4.17022005e-01 7.20324493e-01 1.14374817e-04]
[4.17022005e-01 7.20324493e-01 1.14374817e-04]
[[5 0 0]
 [1 7 6]
 [9 2 4]
 [5 2 4]
 [2 4 7]]
[-2.29230928 -1.41555249  0.8858294   0.63190187  0.04026035]
[[4 5 6]
 [7 8 9]
 [1 2 3]]
